test1 = test/test_tailq
test2 = test/test_tcp

########################## TEST1 #################################
$(test1)_src = test/tailq/tailq.c
$(test1)_inc = -I$(shell pwd)
$(test1)_OBJS := $(patsubst %,$(OBJ_PATH)%,$($(test1)_src:.c=.o))
$(test1)_DEPS := $(patsubst %,$(OBJ_PATH)%,$($(test1)_src:.c=.d))

$(test1): $($(test1)_OBJS)
	@mkdir -p build
	@$(CC) $(CFLAGS) $($(test1)_OBJS) -o $(test1) $(LDFLAGS)

###########################################################

########################## TEST2 #################################
$(test2)_src = test/tcp/tcp.c
$(test2)_inc = -I$(shell pwd)
$(test2)_OBJS := $(patsubst %,$(OBJ_PATH)%,$($(test2)_src:.c=.o))
$(test2)_DEPS := $(patsubst %,$(OBJ_PATH)%,$($(test2)_src:.c=.d))

$(test2): $($(test2)_OBJS)
	@mkdir -p build
	@$(CC) $(CFLAGS) $($(test2)_OBJS) -o $(test2) $(LDFLAGS)

###########################################################

test: start-test $(test1) $(test2) post-test

clean-test:
	$(info [Cleaning])
	@rm -rf build $(test1) $(test2)

start-test:
	$(info ========= Build Test =========)
	$(info [Target] $(test1) $(test2))
	$(info ==============================)

post-test:
	$(info [Generate] $(test1) $(test2).)
	@echo "Done."
	@echo "Running tests..."
	@echo "[RUN] Test: $(test1)"
	@./$(test1)
	@echo "[FINISHED] Test: $(test1)"
	@echo "[RUN] Test: $(test2)"
	@./$(test2)
	@echo "[FINISHED] Test: $(test2)"

-include $($(test1)_DEPS) $($(test2)_DEPS)
